In [102]:
import numpy as np
import pandas as pd

In [103]:
users = pd.read_csv('users.csv')
books = pd.read_csv('Books.csv')
ratings = pd.read_csv('ratings.csv')

C:\Users\ajayn\AppData\Local\Temp\ipykernel_32160\3597061973.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [104]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [105]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [106]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [107]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [108]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [109]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [110]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [111]:
books.duplicated().sum()

0

In [112]:
ratings.duplicated().sum()

0

In [113]:
users.duplicated().sum()

0

In [114]:
users.columns

Index(['User-ID', 'Location', 'Age'], dtype='object')

In [115]:
ratings.columns

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='object')

In [116]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [117]:
books = books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher','Image-URL-M']]

In [118]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [119]:
users.columns

Index(['User-ID', 'Location', 'Age'], dtype='object')

In [120]:
users= users[['User-ID', 'Location']]

In [121]:
users

        User-ID                            Location
0             1                  nyc, new york, usa
1             2           stockton, california, usa
2             3     moscow, yukon territory, russia
3             4           porto, v.n.gaia, portugal
4             5  farnborough, hants, united kingdom
...         ...                                 ...
278853   278854               portland, oregon, usa
278854   278855  tacoma, washington, united kingdom
278855   278856           brampton, ontario, canada
278856   278857           knoxville, tennessee, usa
278857   278858                dublin, n/a, ireland

[278858 rows x 2 columns]

In [122]:
ratings.columns

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='object')

In [123]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-M'],
      dtype='object')

# popularty based recommended

In [124]:
rating_with_books= ratings.merge(books ,on = 'ISBN')

In [125]:
rating_with_books.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...

In [126]:
rating_with_books.shape

(1031136, 8)

In [127]:
rating_with_books.groupby('Book-Title').count()

,User-ID,ISBN,Book-Rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-M
Book-Title,,,,,,,
"A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)",4,4,4,4,4,4,4
Always Have Popsicles,1,1,1,1,1,1,1
Apple Magic (The Collector's series),1,1,1,1,1,1,1
"Ask Lily (Young Women of Faith: Lily Series, Book 5)",1,1,1,1,1,1,1
Beyond IBM: Leadership Marketing and Finance for the 1990s,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...
Ã?Â?lpiraten.,2,2,2,2,2,2,2
Ã?Â?rger mit Produkt X. Roman.,4,4,4,4,4,4,4
Ã?Â?sterlich leben.,1,1,1,1,1,1,1
Ã?Â?stlich der Berge.,3,3,3,3,3,3,3
Ã?Â?thique en toc,2,2,2,2,2,2,2

In [128]:
nums_rating_df = rating_with_books.groupby('Book-Title').count()['Book-Rating'].reset_index()
nums_rating_df.rename(columns={'Book-Rating':'nums_rating'} ,inplace= True)
nums_rating_df

                                               Book-Title  nums_rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [129]:
avg_rating_df = rating_with_books.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'} ,inplace= True)
avg_rating_df

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [130]:
popular_df = nums_rating_df.merge(avg_rating_df ,on='Book-Title')
popular_df

,Book-Title,nums_rating,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [131]:
popular_df[popular_df['nums_rating']>=250]

,Book-Title,nums_rating,avg_rating
764,1984,284,4.454225
818,1st to Die: A Novel,509,3.575639
1048,2nd Chance,356,3.269663
1760,A Bend in the Road,346,3.364162
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
...,...,...,...
233850,White Oleander : A Novel,387,3.506460
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472
234740,Wicked: The Life and Times of the Wicked Witch...,326,3.766871
234951,Wild Animus,2502,1.019584
240860,"\O\"" Is for Outlaw""",269,2.988848

In [132]:
popular_df.sort_values('avg_rating',ascending= False)

,Book-Title,nums_rating,avg_rating
66223,Film Is: The International Free Cinema,1,10.0
123125,More Secrets of Happy Children: Embrace Your P...,1,10.0
96558,Jo's Boys : From the Original Publisher,1,10.0
212107,The Vanished Priestess : An Annie Szabo Mystery,1,10.0
72503,Game and Hunting,1,10.0
...,...,...,...
93628,Invaders of the Planet Earth (Choose Your Own ...,1,0.0
154021,Sammy Discovers the Alphabet (Learn-With-Sammy),1,0.0
154019,Sammy Carducci's Guide to Women,2,0.0
154018,Sammle mir Kiesel am FluÃ?Â?. Mehr als eine Li...,1,0.0
171214,TRAVELLING MAN,1,0.0

In [133]:
popular_df=popular_df.head(50)

In [134]:
popular_df

                                           Book-Title  nums_rating  avg_rating
0    A Light in the Storm: The Civil War Diary of ...            4    2.250000
1                               Always Have Popsicles            1    0.000000
2                Apple Magic (The Collector's series)            1    0.000000
3    Ask Lily (Young Women of Faith: Lily Series, ...            1    8.000000
4    Beyond IBM: Leadership Marketing and Finance ...            1    0.000000
5    Clifford Visita El Hospital (Clifford El Gran...            1    0.000000
6                                        Dark Justice            1   10.000000
7                                            Deceived            2    0.000000
8    Earth Prayers From around the World: 365 Pray...           10    5.000000
9    Final Fantasy Anthology: Official Strategy Gu...            4    5.000000
10   Flight of Fancy: American Heiresses (Zebra Ba...            2    4.000000
11   Garfield Bigger and Better (Garfield (Numbere...            2    3.500000
12                          God's Little Promise Book            2    4.500000
13   Good Wives: Image and Reality in the Lives of...           10    3.200000
14   Goosebumps Monster Edition 1: Welcome to Dead...            9    2.222222
15   Harry Potter and the Bible: The Menace Behind...            1    0.000000
16   Highland Desire (Zebra Splendor Historical Ro...            1    7.000000
17   Hiking the California Coastal Trail: Oregon t...            1    0.000000
18                                       It Takes Two            2    0.000000
19               LA Gallinita Roja/the Little Red Hen            2    0.000000
20   Little Comic Shop of Horrors (Give Yourself G...            4    1.250000
21   Microsoft Application Architecture For Micros...            1    9.000000
22   Murder of a Sleeping Beauty (Scumble River My...           11    3.181818
23                                       Mystery Mile            2    0.000000
24   Nonbook Materials: The Organization of Integr...            1    7.000000
25     Pokemon: The Official Collector's Sticker Book            1    0.000000
26   Q-Space (Star Trek The Next Generation, Book 47)           17    1.941176
27    Q-Zone (Star Trek The Next Generation, Book 48)           11    1.000000
28                  Stories of an Imaginary Childhood            1    0.000000
29                 Summonings: Books of Magic, Vol. 2            2    7.000000
30                       Tales of Terror and Suspense            1    0.000000
31   The Secret of the Old Clock (Nancy Drew, Book 1)            3    3.333333
32   The Tender Commandments : Reflections on the ...            2    0.000000
33                      The Town Cats and Other Tales            1    0.000000
34   This Place Has No Atmosphere (Laurel-Leaf Books)            9    2.000000
35                                        Tough Loser            1    0.000000
36   Travel Companion Chile and Easter Island (Tra...            1    5.000000
37   Twenty Thousand Leagues Under the Sea (Illust...            1    0.000000
38                                 Weird News Stories            2    2.500000
39   Zap!: Science Fair Surprise! (Abracadabra!, B...            1    0.000000
40                      the Devil Will Drag You Under            1    8.000000
41                          !%@ (A Nutshell handbook)            2    3.000000
42                    !Arriba! Comunicacion y cultura            2    4.500000
43  !Trato hecho!: Spanish for Real Life, Combined...            1    5.000000
44                                               !Yo!           11    5.181818
45                 $14 In The Bank (Cathy Collection)            5    1.800000
46                                    $30 Film School            1    8.000000
47                                        $Weet Deal$            1    0.000000
48  $oft Money: The True Power in Our Nation's Cap...            5    5.400000
49       ' Allo 'Allo: the War Diaries of Rene Artois            1    5.000000

In [135]:
popular_df=popular_df.merge(books, on ='Book-Title')

In [136]:
popular_df.drop_duplicates('Book-Title')

,Book-Title,nums_rating,avg_rating,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-M
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000,0590567330,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...
1,Always Have Popsicles,1,0.000000,0964147726,Rebecca Harvin,1994,Rebecca L. Harvin,http://images.amazon.com/images/P/0964147726.0...
2,Apple Magic (The Collector's series),1,0.000000,0942320093,Martina Boudreau,1984,Amer Cooking Guild,http://images.amazon.com/images/P/0942320093.0...
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000,0310232546,Nancy N. Rue,2001,Zonderkidz,http://images.amazon.com/images/P/0310232546.0...
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000,0962295701,Lou Mobley,1989,"Teleonet, Incorporated",http://images.amazon.com/images/P/0962295701.0...
5,Clifford Visita El Hospital (Clifford El Gran...,1,0.000000,0439188970,Norman Bridwell,2000,Scholastic,http://images.amazon.com/images/P/0439188970.0...
6,Dark Justice,1,10.000000,0399151788,Jack Higgins,2004,Putnam Publishing Group,http://images.amazon.com/images/P/0399151788.0...
7,Deceived,2,0.000000,0786000015,Carla Simpson,1994,Pinnacle Books,http://images.amazon.com/images/P/0786000015.0...
8,Earth Prayers From around the World: 365 Pray...,10,5.000000,006250746X,Elizabeth Roberts,1991,HarperSanFrancisco,http://images.amazon.com/images/P/006250746X.0...
9,Final Fantasy Anthology: Official Strategy Gu...,4,5.000000,1566869250,David Cassady,1999,BradyGames,http://images.amazon.com/images/P/1566869250.0...
10,Flight of Fancy: American Heiresses (Zebra Ba...,2,4.000000,082177350X,Tracy Cozzens,2002,Kensington Publishing Corporation,http://images.amazon.com/images/P/082177350X.0...
11,Garfield Bigger and Better (Garfield (Numbere...,2,3.500000,0345407709,Jim Davis,1996,Ballantine Books,http://images.amazon.com/images/P/0345407709.0...
12,God's Little Promise Book,2,4.500000,0849951577,Word Pub,1995,J Countryman Books,http://images.amazon.com/images/P/0849951577.0...
13,Good Wives: Image and Reality in the Lives of...,10,3.200000,0679732578,Laurel Thatcher Ulrich,1991,Vintage Books USA,http://images.amazon.com/images/P/0679732578.0...
14,Goosebumps Monster Edition 1: Welcome to Dead...,9,2.222222,0590509950,R. L. Stine,1995,Scholastic Paperbacks (T),http://images.amazon.com/images/P/0590509950.0...
15,Harry Potter and the Bible: The Menace Behind...,1,0.000000,0889652015,Richard Abanes,2001,Horizon Books Publishers,http://images.amazon.com/images/P/0889652015.0...
16,Highland Desire (Zebra Splendor Historical Ro...,1,7.000000,0821760580,Joyce Carlow,1998,Zebra Books,http://images.amazon.com/images/P/0821760580.0...
17,Hiking the California Coastal Trail: Oregon t...,1,0.000000,0939431181,Bob Lorentzen,1997,Bored Feet Publications,http://images.amazon.com/images/P/0939431181.0...
18,It Takes Two,2,0.000000,0590853112,Nancy Krlik,1995,Scholastic,http://images.amazon.com/images/P/0590853112.0...
19,LA Gallinita Roja/the Little Red Hen,2,0.000000,0590449273,Lucinda McQueen,1995,Scholastic,http://images.amazon.com/images/P/0590449273.0...
20,Little Comic Shop of Horrors (Give Yourself G...,4,1.250000,059093483X,R. L. Stine,1997,Apple (Scholastic),http://images.amazon.com/images/P/059093483X.0...
21,Microsoft Application Architecture For Micros...,1,9.000000,0735618372,Microsoft Corporation Staff,2004,Microsoft Press,http://images.amazon.com/images/P/0735618372.0...
22,Murder of a Sleeping Beauty (Scumble River My...,11,3.181818,0451205480,Denise Swanson,2002,Signet Book,http://images.amazon.com/images/P/0451205480.0...
23,Mystery Mile,2,0.000000,1567230148,Margery Allingham,1994,Yestermorrow Inc,http://images.amazon.com/images/P/1567230148.0...
24,Nonbook Materials: The Organization of Integr...,1,7.000000,0888020910,Jean Riddle Weihs,1973,Canadian Library Association,http://images.amazon.com/images/P/0888020910.0...
25,Pokemon: The Official Collector's Sticker Book,1,0.000000,0439106591,Maria S. Barbo,1999,Scholastic,http://images.amazon.com/images/P/0439106591.0...
26,"Q-Space (Star Trek The Next Generation, Book 47)",17,1.941176,0671019155,Greg Cox,1998,Star Trek,http://images.amazon.com/images/P/0671019155.0...
27,"Q-Zone (Star Trek The Next Generation, Book 48)",11,1.000000,067101921X,Greg Cox,1998,Star Trek,http://images.amazon.com/images/P/067101921X.0...
28,Stories of an Imaginary Childhood,1,0.000000,0810110318,Melvin Jules Bukiet,1991,Northwestern Univ Pr,http://images.amazon.com/images/P/0810110318.0...
29,"Summonings: Books of Magic, Vol. 2",2,7.000000,1563892650,John Ney Rieber,1996,DC Comics,http://images.amazon.com/images/P/1563892650.0...
30,Tales of Terror and Suspense,1,0.000000,1561568805,Allen Edgar,1998,Kidsbooks,http://images.amazon.com/images/P/1561568805.0...
31,"The Secret of the Old Clock (Nancy Drew, Book 1)",3,3.333333,0807207543,Carolyn Keene,2002,Imagination Studio,http://images.amazon.com/images/P/0807207543.0...
32,The Tender Commandments : Reflections on the ...,2,0.000000,1576737772,Ron Mehl,2001,Multnomah,http://images.amazon.com/images/P/1576737772.0...
33,The Town Cats and Other Tales,1,0.000000,044048989X,Lloyd Alexander,1990,Yearling Books,http://images.amazon.com/images/P/044048989X.0...
34,This Place Has No Atmosphere (Laurel-Leaf Books),9,2.000000,0440987261,Paula Danziger,1987,Random House Childrens Pub,http://images.amazon.com/images/P/0440987261.0...
35,Tough Loser,1,0.000000,0670856193,Barthe Declements,1994,Viking Books,http://images.amazon.com/images/P/0670856193.0...
36,Travel Companion Chile and Easter Island (Tra...,1,5.000000,0646060422,Gerry Leitner,1996,Hunter Publishing,http://images.amazon.com/images/P/0646060422.0...
37,Twenty Thousand Leagues Under the Sea (Illust...,1,0.000000,0942025857,Jules Verne,1990,Kidsbooks.Com,http://images.amazon.com/images/P/0942025857.0...
38,Weird News Stories,2,2.500000,0752517783,Colin Wilson,1996,Siena,http://images.amazon.com/images/P/0752517783.0...
39,"Zap!: Science Fair Surprise! (Abracadabra!, B...",1,0.000000,0439389364,Peter Lerangis,2003,Scholastic,http://images.amazon.com/images/P/0439389364.0...
40,the Devil Will Drag You Under,1,8.000000,0345279263,Jack L Chalker,1979,Ballantine Books,http://images.amazon.com/images/P/0345279263.0...
41,!%@ (A Nutshell handbook),2,3.000000,1565920465,Donnalyn Frey,1994,O'Reilly,http://images.amazon.com/images/P/1565920465.0...
43,!Arriba! Comunicacion y cultura,2,4.500000,0133989429,Eduardo Zayas-Bazan,1996,Prentice Hall,http://images.amazon.com/images/P/0133989429.0...
44,"!Trato hecho!: Spanish for Real Life, Combined...",1,5.000000,013327974X,John T. McMinn,1995,Prentice Hall,http://images.amazon.com/images/P/013327974X.0...
45,!Yo!,11,5.181818,0452279186,Julia Alvarez,1997,Plume Books,http://images.amazon.com/images/P/0452279186.0...
46,$14 In The Bank (Cathy Collection),5,1.800000,0836218205,Cathy Guisewite,1990,Andrews McMeel Publishing,http://images.amazon.com/images/P/0836218205.0...
47,$30 Film School,1,8.000000,1592000673,Michael W. Dean,2003,Muska &amp; Lipman Publishing,http://images.amazon.com/images/P/1592000673.0...
48,$Weet Deal$,1,0.000000,0812506448,Brian Lysaght,1986,Tor Books,http://images.amazon.com/images/P/0812506448.0...
49,$oft Money: The True Power in Our Nation's Cap...,5,5.400000,1588204030,E. L. Burton,2000,1stBooks Library,http://images.amazon.com/images/P/1588204030.0...
50,' Allo 'Allo: the War Diaries of Rene Artois,1,5.000000,0563208422,John Haselden,1989,BBC Consumer Publishing,http://images.amazon.com/images/P/0563208422.0...

In [182]:
popular_df['Image-URL-M'][0]

'http://images.amazon.com/images/P/0590567330.01.MZZZZZZZ.jpg'

In [137]:
popular_df.columns

Index(['Book-Title', 'nums_rating', 'avg_rating', 'ISBN', 'Book-Author',
       'Year-Of-Publication', 'Publisher', 'Image-URL-M'],
      dtype='object')

In [138]:
popular_df= popular_df[['Book-Title','Book-Author','Image-URL-M','nums_rating', 'avg_rating']]

In [139]:
popular_df

,Book-Title,Book-Author,Image-URL-M,nums_rating,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,Karen Hesse,http://images.amazon.com/images/P/0590567330.0...,4,2.250000
1,Always Have Popsicles,Rebecca Harvin,http://images.amazon.com/images/P/0964147726.0...,1,0.000000
2,Apple Magic (The Collector's series),Martina Boudreau,http://images.amazon.com/images/P/0942320093.0...,1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",Nancy N. Rue,http://images.amazon.com/images/P/0310232546.0...,1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,Lou Mobley,http://images.amazon.com/images/P/0962295701.0...,1,0.000000
5,Clifford Visita El Hospital (Clifford El Gran...,Norman Bridwell,http://images.amazon.com/images/P/0439188970.0...,1,0.000000
6,Dark Justice,Jack Higgins,http://images.amazon.com/images/P/0399151788.0...,1,10.000000
7,Deceived,Carla Simpson,http://images.amazon.com/images/P/0786000015.0...,2,0.000000
8,Earth Prayers From around the World: 365 Pray...,Elizabeth Roberts,http://images.amazon.com/images/P/006250746X.0...,10,5.000000
9,Final Fantasy Anthology: Official Strategy Gu...,David Cassady,http://images.amazon.com/images/P/1566869250.0...,4,5.000000
10,Flight of Fancy: American Heiresses (Zebra Ba...,Tracy Cozzens,http://images.amazon.com/images/P/082177350X.0...,2,4.000000
11,Garfield Bigger and Better (Garfield (Numbere...,Jim Davis,http://images.amazon.com/images/P/0345407709.0...,2,3.500000
12,God's Little Promise Book,Word Pub,http://images.amazon.com/images/P/0849951577.0...,2,4.500000
13,Good Wives: Image and Reality in the Lives of...,Laurel Thatcher Ulrich,http://images.amazon.com/images/P/0679732578.0...,10,3.200000
14,Goosebumps Monster Edition 1: Welcome to Dead...,R. L. Stine,http://images.amazon.com/images/P/0590509950.0...,9,2.222222
15,Harry Potter and the Bible: The Menace Behind...,Richard Abanes,http://images.amazon.com/images/P/0889652015.0...,1,0.000000
16,Highland Desire (Zebra Splendor Historical Ro...,Joyce Carlow,http://images.amazon.com/images/P/0821760580.0...,1,7.000000
17,Hiking the California Coastal Trail: Oregon t...,Bob Lorentzen,http://images.amazon.com/images/P/0939431181.0...,1,0.000000
18,It Takes Two,Nancy Krlik,http://images.amazon.com/images/P/0590853112.0...,2,0.000000
19,LA Gallinita Roja/the Little Red Hen,Lucinda McQueen,http://images.amazon.com/images/P/0590449273.0...,2,0.000000
20,Little Comic Shop of Horrors (Give Yourself G...,R. L. Stine,http://images.amazon.com/images/P/059093483X.0...,4,1.250000
21,Microsoft Application Architecture For Micros...,Microsoft Corporation Staff,http://images.amazon.com/images/P/0735618372.0...,1,9.000000
22,Murder of a Sleeping Beauty (Scumble River My...,Denise Swanson,http://images.amazon.com/images/P/0451205480.0...,11,3.181818
23,Mystery Mile,Margery Allingham,http://images.amazon.com/images/P/1567230148.0...,2,0.000000
24,Nonbook Materials: The Organization of Integr...,Jean Riddle Weihs,http://images.amazon.com/images/P/0888020910.0...,1,7.000000
25,Pokemon: The Official Collector's Sticker Book,Maria S. Barbo,http://images.amazon.com/images/P/0439106591.0...,1,0.000000
26,"Q-Space (Star Trek The Next Generation, Book 47)",Greg Cox,http://images.amazon.com/images/P/0671019155.0...,17,1.941176
27,"Q-Zone (Star Trek The Next Generation, Book 48)",Greg Cox,http://images.amazon.com/images/P/067101921X.0...,11,1.000000
28,Stories of an Imaginary Childhood,Melvin Jules Bukiet,http://images.amazon.com/images/P/0810110318.0...,1,0.000000
29,"Summonings: Books of Magic, Vol. 2",John Ney Rieber,http://images.amazon.com/images/P/1563892650.0...,2,7.000000
30,Tales of Terror and Suspense,Allen Edgar,http://images.amazon.com/images/P/1561568805.0...,1,0.000000
31,"The Secret of the Old Clock (Nancy Drew, Book 1)",Carolyn Keene,http://images.amazon.com/images/P/0807207543.0...,3,3.333333
32,The Tender Commandments : Reflections on the ...,Ron Mehl,http://images.amazon.com/images/P/1576737772.0...,2,0.000000
33,The Town Cats and Other Tales,Lloyd Alexander,http://images.amazon.com/images/P/044048989X.0...,1,0.000000
34,This Place Has No Atmosphere (Laurel-Leaf Books),Paula Danziger,http://images.amazon.com/images/P/0440987261.0...,9,2.000000
35,Tough Loser,Barthe Declements,http://images.amazon.com/images/P/0670856193.0...,1,0.000000
36,Travel Companion Chile and Easter Island (Tra...,Gerry Leitner,http://images.amazon.com/images/P/0646060422.0...,1,5.000000
37,Twenty Thousand Leagues Under the Sea (Illust...,Jules Verne,http://images.amazon.com/images/P/0942025857.0...,1,0.000000
38,Weird News Stories,Colin Wilson,http://images.amazon.com/images/P/0752517783.0...,2,2.500000
39,"Zap!: Science Fair Surprise! (Abracadabra!, B...",Peter Lerangis,http://images.amazon.com/images/P/0439389364.0...,1,0.000000
40,the Devil Will Drag You Under,Jack L Chalker,http://images.amazon.com/images/P/0345279263.0...,1,8.000000
41,!%@ (A Nutshell handbook),Donnalyn Frey,http://images.amazon.com/images/P/1565920465.0...,2,3.000000
42,!%@ (A Nutshell handbook),Donnalyn Frey,http://images.amazon.com/images/P/1565920317.0...,2,3.000000
43,!Arriba! Comunicacion y cultura,Eduardo Zayas-Bazan,http://images.amazon.com/images/P/0133989429.0...,2,4.500000
44,"!Trato hecho!: Spanish for Real Life, Combined...",John T. McMinn,http://images.amazon.com/images/P/013327974X.0...,1,5.000000
45,!Yo!,Julia Alvarez,http://images.amazon.com/images/P/0452279186.0...,11,5.181818
46,$14 In The Bank (Cathy Collection),Cathy Guisewite,http://images.amazon.com/images/P/0836218205.0...,5,1.800000
47,$30 Film School,Michael W. Dean,http://images.amazon.com/images/P/1592000673.0...,1,8.000000
48,$Weet Deal$,Brian Lysaght,http://images.amazon.com/images/P/0812506448.0...,1,0.000000
49,$oft Money: The True Power in Our Nation's Cap...,E. L. Burton,http://images.amazon.com/images/P/1588204030.0...,5,5.400000
50,' Allo 'Allo: the War Diaries of Rene Artois,John Haselden,http://images.amazon.com/images/P/0563208422.0...,1,5.000000

# Collabrating filtering based recommender system

In [140]:
rating_with_books.columns

Index(['User-ID', 'ISBN', 'Book-Rating', 'Book-Title', 'Book-Author',
       'Year-Of-Publication', 'Publisher', 'Image-URL-M'],
      dtype='object')

In [141]:
x = rating_with_books.groupby('User-ID').count()['Book-Title']>200
user_rating = x[x].index

In [142]:
user_rating

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=811)

In [143]:
filtering_rating = rating_with_books[rating_with_books['User-ID'].isin(user_rating)]

In [144]:
filtering_rating.shape

(474007, 8)

In [145]:
rating_with_books.shape

(1031136, 8)

In [146]:
y = filtering_rating.groupby('Book-Title').count()['Book-Rating']>=50

In [147]:
famous_books = y[y].index
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [148]:
  final_ratings = filtering_rating[filtering_rating['Book-Title'].isin(famous_books)]

In [149]:
final_ratings.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1163,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...
1165,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...
1168,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...
1174,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...
...,...,...,...,...,...,...,...,...
1029196,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031354.0...
1029197,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031362.0...
1029270,275970,1573229725,0,Fingersmith,Sarah Waters,2002,Riverhead Books,http://images.amazon.com/images/P/1573229725.0...
1029309,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...
1029310,275970,1586212230,0,Naked,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586212230.0...

In [150]:
pt= final_ratings.pivot_table(index= 'Book-Title' , columns= 'User-ID' , values = 'Book-Rating')

In [151]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [152]:
pt.fillna(0, inplace= True)

In [153]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [154]:
from sklearn.metrics.pairwise import cosine_similarity

In [155]:
similarity_score = cosine_similarity(pt)

In [156]:
similarity_score

array([[1.        , 0.10255025, 0.01220856, ..., 0.12110367, 0.07347567,
        0.04316046],
       [0.10255025, 1.        , 0.2364573 , ..., 0.07446129, 0.16773875,
        0.14263397],
       [0.01220856, 0.2364573 , 1.        , ..., 0.04558758, 0.04938579,
        0.10796119],
       ...,
       [0.12110367, 0.07446129, 0.04558758, ..., 1.        , 0.07085128,
        0.0196177 ],
       [0.07347567, 0.16773875, 0.04938579, ..., 0.07085128, 1.        ,
        0.10602962],
       [0.04316046, 0.14263397, 0.10796119, ..., 0.0196177 , 0.10602962,
        1.        ]])

In [157]:
similarity_score.shape

(706, 706)

In [205]:
def recommended(book_name):
    #fetch index
    index = np.where(pt.index== book_name)[0][0]
    similar_item = sorted(list(enumerate(similarity_score[index])),key = lambda x:x[1], reverse = True)[1:5]
    data= []
    for i in similar_item:
        item = []
        temp_df = books[books['Book-Title']== pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))

        data.append(item)
    return data

In [206]:
recommended('1st to Die: A Novel')

[['Along Came a Spider (Alex Cross Novels)',
  'James Patterson',
  'http://images.amazon.com/images/P/0446364193.01.MZZZZZZZ.jpg'],
 ['Roses Are Red (Alex Cross Novels)',
  'James Patterson',
  'http://images.amazon.com/images/P/0446605484.01.MZZZZZZZ.jpg'],
 ['Pop Goes the Weasel',
  'James Patterson',
  'http://images.amazon.com/images/P/0316693286.01.MZZZZZZZ.jpg'],
 ['Violets Are Blue',
  'James Patterson',
  'http://images.amazon.com/images/P/0446611212.01.MZZZZZZZ.jpg']]

In [183]:
pt.index[3]

'4 Blondes'

In [184]:
import pickle
pickle.dump(popular_df, open('popular.pkl','wb'))

In [185]:
popular_df.columns

Index(['Book-Title', 'Book-Author', 'Image-URL-M', 'nums_rating',
       'avg_rating'],
      dtype='object')

In [204]:
pickle.dump(pt, open('pt.pkl','wb'))
pickle.dump(books, open('books.pkl','wb'))
pickle.dump(similarity_score, open('similarity_score.pkl','wb'))